services:
  # Web Service (Flask for upload.html) - Starter Plan
  - type: web
    name: exam-surveillance-web
    plan: starter  # 🚀 Upgraded from free
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /tmp/models
    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app  # Production-ready
    envVars:
      - key: FIREBASE_STORAGE_BUCKET
        value: "exam-surveillance.firebasestorage.app"  # ✅ Standard Firebase format
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-key.json
    healthCheckPath: /health  # Optional: Add a /health route in server.py

  # Worker Service (main.py analysis) - Starter Plan  
  - type: worker
    name: exam-surveillance-worker
    plan: starter  # 🚀 Upgraded from free
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /tmp/models
    startCommand: python main.py
    envVars:
      - key: FIREBASE_STORAGE_BUCKET
        syncEnv: true  # Shares web service's bucket
      - key: GOOGLE_APPLICATION_CREDENTIALS
        syncEnv: true
      - key: TELEGRAM_BOT_TOKEN
        value: "7556496216:AAEnklt80gw-kF7ZHFRA2o7D91YDKCeXMNU"
      - key: TELEGRAM_CHAT_ID
        value: "1042670358"
      - key: PYTHONUNBUFFERED
        value: "1"