services:
  # Web Service (Flask)
  - type: web
    name: exam-surveillance-web
    plan: starter
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p /tmp/models
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 server:app  # Added timeout
    envVars:
      - key: FIREBASE_STORAGE_BUCKET
        value: "exam-surveillance.firebasestorage.app"  # 🚨 Changed to .appspot.com format
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-key.json
    healthCheckPath: /health

  # Worker Service
  - type: worker
    name: exam-surveillance-worker
    plan: starter
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p /tmp/models
    startCommand: python main.py
    envVars:
      - key: FIREBASE_STORAGE_BUCKET
        syncEnv: true
      - key: GOOGLE_APPLICATION_CREDENTIALS
        syncEnv: true
      - key: TELEGRAM_BOT_TOKEN
        value: "7556496216:AAEnklt80gw-kF7ZHFRA2o7D91YDKCeXMNU"
      - key: TELEGRAM_CHAT_ID
        value: "1042670358"
      - key: PYTHONUNBUFFERED
        value: "1"